---

- name: add common objects to stretched template
  hosts: mso
  connection: local
  gather_facts: false

  vars_files:
    - vars/mso-aws-stretched.yaml
    - vars/mso-schema-templates.yaml

  tasks:
    - name: Set vars
      set_fact: 
        mso_info: &mso_info
          host: '{{ host }}'
          username: '{{ username }}'
          password: '{{ password }}'
          login_domain: "{{ login_domain }}"
          validate_certs: no

    - name: Add a new filter entry
      cisco.mso.mso_schema_template_filter_entry:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_stretched }}"
        filter: "{{ item.name }}"
        entry: "{{ item.name }}"
        ethertype: 'ip'
        ip_protocol: "{{ item.protocol }}"
        destination_from: "{{ item.port | default(omit) }}"
        destination_to: "{{ item.port | default(omit) }}"
        state: present
      loop: "{{ filters }}"
      delegate_to: localhost

    - name: Add a new contract filter
      cisco.mso.mso_schema_template_contract_filter:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_stretched }}"
        contract: "{{ item.name }}"
        contract_scope: global
        filter: "{{ item.filter }}"
        state: present
      loop: "{{ contract_def }}"
      delegate_to: localhost