---

- name: add Application Profile and EPG
  hosts: mso
  connection: local
  gather_facts: false

  vars_files:
    - vars/mso-onprem-db.yaml
    - vars/mso-schema-templates.yaml
    - vars/mso-aws-stretched.yaml

  tasks:
    - name: Set vars
      set_fact: 
        mso_info: &mso_info
          host: '{{ host }}'
          username: '{{ username }}'
          password: '{{ password }}'
          login_domain: "{{ login_domain }}"
          validate_certs: no

    - name: Add a new VRF
      cisco.mso.mso_schema_template_vrf:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        vrf: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Add a new BD
      cisco.mso.mso_schema_template_bd:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        bd: "{{ bd_1 }}"
        layer2_stretch: 'no'
        layer2_unknown_unicast: flood
        layer3_multicast: 'no'
        vrf:
          name: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Add a new subnet to a BD
      cisco.mso.mso_schema_site_bd_subnet:
        <<: *mso_info
        schema: "{{ schema }}"
        site: "{{ site_onprem }}"
        template: "{{ template_onprem }}"
        bd: 'db_bd'
        subnet: "{{ subnet_1 }}"
        scope: 'public'
        shared: 'yes'
        state: present
      delegate_to: localhost

    - name: Add a Application Profile
      cisco.mso.mso_schema_template_anp:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        state: present
      delegate_to: localhost

    - name: Add a EPG
      cisco.mso.mso_schema_template_anp_epg:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        epg: "{{ epg_1 }}"
        bd: 
          name: "{{ bd_1 }}"
        vrf:
          name: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Attach contracts to EPG
      cisco.mso.mso_schema_template_anp_epg_contract:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ item.anp }}"
        epg: "{{ item.epg }}"
        contract:
          name: "{{ item.contract }}"
          type: "{{ item.direction }}"
          template: "{{ template_stretched }}"
        state: present
      loop: "{{ contracts_epg_attachment }}"
      delegate_to: localhost