---

- name: add Application Profile and EPG
  hosts: mso
  connection: local
  gather_facts: false

  vars_files:
    - vars/mso-onprem.yaml
    - vars/mso-schema-templates.yaml
    - vars/mso-aws-stretched.yaml

  tasks:
    - name: Set vars
      set_fact: 
        mso_info: &mso_info
          host: '{{ host }}'
          username: '{{ username }}'
          password: '{{ password }}'
          login_domain: "{{ login_domain }}"
          validate_certs: no

    - name: Add a new VRF
      cisco.mso.mso_schema_template_vrf:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        vrf: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Add a new DB Bridge Domain
      cisco.mso.mso_schema_template_bd:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        bd: "{{ bd_1 }}"
        layer2_stretch: 'no'
        layer2_unknown_unicast: flood
        layer3_multicast: 'no'
        vrf:
          name: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Add a new BD REST APP
      cisco.mso.mso_schema_template_bd:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        bd: "{{ bd_2 }}"
        layer2_stretch: 'no'
        layer2_unknown_unicast: flood
        layer3_multicast: 'no'
        vrf:
          name: "{{ vrf }}"
        state: present
      delegate_to: localhost

    # - name: Add a new subnet to a BD
    #   cisco.mso.mso_schema_site_bd_subnet:
    #     <<: *mso_info
    #     schema: "{{ schema }}"
    #     template: "{{ template_onprem }}"
    #     site: "{{ site_onprem }}"
    #     bd: "{{ bd_1 }}"
    #     subnet: "{{ subnet_1 }}"
    #     scope: 'public'
    #     shared: 'yes'
    #     state: present
    #   delegate_to: localhost

    # - name: Add a new subnet to a BD
    #   cisco.mso.mso_schema_site_bd_subnet:
    #     <<: *mso_info
    #     schema: "{{ schema }}"
    #     template: "{{ template_onprem }}"
    #     site: "{{ site_onprem }}"
    #     bd: "{{ bd_2 }}"
    #     subnet: "{{ subnet_2 }}"
    #     scope: 'public'
    #     shared: 'yes'
    #     state: present
    #   delegate_to: localhost

    - name: Add a Application Profile
      cisco.mso.mso_schema_template_anp:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        state: present
      delegate_to: localhost

    - name: Add a EPG
      cisco.mso.mso_schema_template_anp_epg:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        epg: "{{ epg_1 }}"
        bd: 
          name: "{{ bd_1 }}"
        vrf:
          name: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Add a EPG
      cisco.mso.mso_schema_template_anp_epg:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        epg: "{{ epg_2 }}"
        bd: 
          name: "{{ bd_2 }}"
        vrf:
          name: "{{ vrf }}"
        state: present
      delegate_to: localhost

    - name: Add a new domain to a site EPG
      cisco.mso.mso_schema_site_anp_epg_domain:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        epg: "{{ epg_1 }}"
        site: "{{ site_onprem }}"
        domain_association_type: vmmDomain
        domain_profile: 'ACI-DMZ-VDS02'
        deployment_immediacy: lazy
        resolution_immediacy: lazy
        state: present
      delegate_to: localhost

    - name: Add a new domain to a site EPG
      cisco.mso.mso_schema_site_anp_epg_domain:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ anp_1 }}"
        epg: "{{ epg_2 }}"
        site: "{{ site_onprem }}"
        domain_association_type: vmmDomain
        domain_profile: 'ACI-DMZ-VDS02'
        deployment_immediacy: lazy
        resolution_immediacy: lazy
        state: present
      delegate_to: localhost

    - name: Attach contracts to EPG
      cisco.mso.mso_schema_template_anp_epg_contract:
        <<: *mso_info
        schema: "{{ schema }}"
        template: "{{ template_onprem }}"
        anp: "{{ item.anp }}"
        epg: "{{ item.epg }}"
        contract:
          name: "{{ item.contract }}"
          type: "{{ item.direction }}"
          template: "{{ template_stretched }}"
        state: present
      loop: "{{ contracts_epg_attachment }}"
      delegate_to: localhost
