---
- name: deploy MQTT ec2 instance
  hosts: localhost
  connection: local

  vars_files:
    - vars/mso-aws-mqtt.yaml
    - vars/ec2-mqtt.yaml

  tasks:
    - name: Set vars
      set_fact: 
        mso_info: &aws_info
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          security_token: "{{ security_token }}"
          region: "{{ aws_region }}"

    # - name: assume sts role
    #   community.aws.sts_assume_role:
    #     <<: *aws_info
    #     role_arn: "arn:aws:iam::180081511176:role/PowerUserRole"
    #     role_session_name: "thc-tenant"
    #   register: assumed_role

    - name: Obtain default VPC information
      ec2_vpc_net_info:
        <<: *aws_info
        # aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        # aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        # security_token: "{{ assumed_role.sts_creds.session_token }}"
      filters:
          "cidr": "{{ cidr }}"
      register: vpc
    
    - name: Obtain subnets for default VPC
      ec2_vpc_subnet_facts:
        <<: *aws_info
        filters:
          vpc-id: "{{ vpc['vpcs'][0]['vpc_id'] }}"
      register: subnet_info
    
    # Use jinja to select a random subnet from the list of subnet ids
    - set_fact:
        vpc_id: "{{ vpc['vpcs'][0]['vpc_id'] }}"
        random_subnet: "{{ subnet_info.subnets|map(attribute='id')|list|random }}"

    - name: deploy ec2 instance
      ec2:
        <<: *aws_info
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        count: 1
        instance_tags:
          epg: "{{ epg_1 }}"
        vpc_subnet_id: "{{ random_subnet }}"
        assign_public_ip: yes
      register: ec2

    - name: Add the newly created EC2 instance(s) to the local host group
      lineinfile:
        path: ./hosts
        line: "{{ item.public_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=key/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
        insertafter: '^\[ec2-mqtt\]'
      with_items: "{{ ec2.instances }}"