---
- name: deploy front ec2 instance
  hosts: ec2-front
  vars_files:
    - vars/ec2-front.yaml

  tasks:
    - name: Install packages (yum)
      yum:
        name: 
        - docker
        - git
        state: present
      become: yes
    
    - name: " Starting and Enabling Docker service"
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Install NGINX
      shell: sudo amazon-linux-extras install -y nginx1
      become: yes
    
    - name: clone git repo
      git:
        repo: 'https://github.com/fwardzic/mso-cloud-ansible.git'
        dest: /home/ec2-user/mso-cloud-ansible
      become: no
      
    - name: copy nginx
      copy: 
        src: /home/ec2-user/mso-cloud-ansible/Frontend/Nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: yes
      become: yes
    
    - name: run NGINX
      systemd:
        name: nginx
        state: started
        enabled: yes
      become: yes
      
    - name: run frontend
      shell: 'docker run -d -p 5061:5061 --env BACKEND_PORT=5050 --env BACKEND_HOST=10.56.233.194 eu.gcr.io/fwardz001-poc-ci1s/frontend_server:latest'
      become: yes

    # - name: run frontend
    #   community.general.docker_container:
    #     name: frontend
    #     image: eu.gcr.io/fwardz001-poc-ci1s/frontend_server:latest
    #     ports: 5061:5061
    #     env:
    #       BACKEND_HOST: '10.56.234.10'
    #       BACKEND_PORT: '5050'
    #     state: present


        
        
