---
- name: deploy nginx ec2 instance
  hosts: ec2-front

  tasks:
    - name: Install packages (yum)
      yum:
        name:
          - php
          - php-fpm
          - git
        state: present
      become: yes
    
    - name: Install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present
      become: yes

    - name: Install NGINX
      shell: sudo amazon-linux-extras install -y nginx1
      become: yes

    - name: clone git repo
      git:
        repo: 'https://github.com/fwardzic/mso-cloud-ansible.git'
        dest: /home/ec2-user/mso-cloud-ansible
      become: no
    
    - name: copy nginx config files
      copy: 
        src: /home/ec2-user/mso-cloud-ansible/nginx/default.conf
        dest: /etc/nginx/conf.d/
        remote_src: yes
      become: yes

    - name: copy php config files
      copy: 
        src: /home/ec2-user/mso-cloud-ansible/nginx/www.conf
        dest: /etc/php-fpm.d/
        remote_src: yes
      become: yes

    - name: copy index.php config files
      copy: 
        src: /home/ec2-user/mso-cloud-ansible/nginx/index.php
        dest: /var/www/html
        remote_src: yes
      become: yes

    - name: run NGINX
      systemd:
        name: nginx
        state: started
        enabled: yes
      become: yes
    
    - name: run php-fpm
      systemd:
        name: php-fpm
        state: started
        enabled: yes
      become: yes